- hosts: localhost
  pre_tasks:
    - name: Get current time
      shell: "date +%s"
      register: date
    - set_fact:
        start_time: "{{ date.stdout }}"

    - name: Get hash of current commit
      shell: |
        git rev-parse --short HEAD
      register: gitRevParse
    - set_fact:
        hash: "{{ gitRevParse.stdout }}"
    - set_fact:
        output_path: "output/{{ hash }}/{{ _iteration }}/{{ _index }}"
    - name: Ensure output directory exists
      file:
        path: "{{ output_path }}"
        state: directory
    - name: Copy iteration config to output directory
      copy:
        src: "{{ _config_path }}"
        dest: "{{ output_path }}/config.yml"
    - name: Remove original iteration config
      file:
        path: "{{ _config_path }}"
        state: absent
    - import_tasks: setup_nodes.yml

# DOWNLOAD, COMPILE, AND SET UP DEPENDENCIES
- hosts: client
  gather_facts: False
  tasks:
    - import_tasks: setup_yardstick.yml
- hosts: server
  gather_facts: False
  tasks:
    - import_tasks: setup_opencraft.yml
